### ISSUE TITLE
Support for server side rendering

### ISSUE THREAD

**Issue by oyeanuj** [core-process/viewportwatch#1]
Hi @core-process, thank you for putting out this library - looks super useful. 

I am wondering if you can add support for when used in server environments? Right now including the library throws error since `window` is undefined. Ideally, the library should be checking to see if `window` is defined before using any of its methods or attributes.

FWIW, I am using with React where the page is first getting rendered on the server and then the client.

**Comment by core-process** [comment]
@oyeanuj thanks for your message. I will add this check later today.

**Comment by core-process** [comment]
@oyeanuj I published a new version of `viewportwatch` which is able to deal with non-browser environments. The interface is the same (`dimension`, `on`, `off`, `once`) as in a browser environment, but it will never issue an event and `dimensions()` returns the following fixed value:

```js
import vw from 'viewportwatch';

vw.dimensions()
->  { current: { width: null, height: null },
      maximum: { width: null, height: null },
      minimum: { width: null, height: null }
    }
```

Does that work for you?

**Comment by core-process** [comment]
Closing issue now. Please re-open if further actions are required.

**Comment by oyeanuj** [comment]
@core-process Perfect, thank you!
